// <auto-generated />
using EvaCoreWeb.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EvaCoreWeb.Migrations
{
    [DbContext(typeof(EvaCoreWebContext))]
    [Migration("20200908204035_Inicial")]
    partial class Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("EvaCoreWeb.Models.Classificacao", b =>
                {
                    b.Property<int>("isn_classificacao")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("dsc_classificacao");

                    b.Property<int>("isn_status_classificacao");

                    b.HasKey("isn_classificacao");

                    b.ToTable("Classificacao");
                });

            modelBuilder.Entity("EvaCoreWeb.Models.Codigo", b =>
                {
                    b.Property<int>("isn_codigo")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("dsc_codigo");

                    b.Property<string>("dsc_codigo_de_barra");

                    b.Property<int>("isn_grupo");

                    b.Property<int>("isn_status_codigo");

                    b.Property<int>("isn_subgrupo");

                    b.Property<int>("isn_unidade_medida_estoque");

                    b.Property<double>("qtd_codigo");

                    b.Property<double>("val_preco_venda");

                    b.Property<double>("val_ultima_compra");

                    b.Property<double>("val_ultimo_custo_medio");

                    b.HasKey("isn_codigo");

                    b.ToTable("Codigo");
                });

            modelBuilder.Entity("EvaCoreWeb.Models.Grupo", b =>
                {
                    b.Property<int>("isn_grupo")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("dsc_grupo");

                    b.Property<int>("isn_status_grupo");

                    b.HasKey("isn_grupo");

                    b.ToTable("Grupo");
                });

            modelBuilder.Entity("EvaCoreWeb.Models.SubGrupo", b =>
                {
                    b.Property<int>("isn_subgrupo")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("dsc_subgrupo");

                    b.Property<int>("isn_status_subgrupo");

                    b.HasKey("isn_subgrupo");

                    b.ToTable("SubGrupo");
                });

            modelBuilder.Entity("EvaCoreWeb.Models.Tag", b =>
                {
                    b.Property<int>("isn_tag")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("dsc_tag");

                    b.Property<int>("isn_status_tag");

                    b.HasKey("isn_tag");

                    b.ToTable("Tag");
                });

            modelBuilder.Entity("EvaCoreWeb.Models.UnidadeMedidaEstoque", b =>
                {
                    b.Property<int>("isn_unidade_medida_estoque")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("cod_unidade_medida_estoque");

                    b.Property<string>("dsc_unidade_medida_estoque");

                    b.Property<int>("isn_status_unidade_medida_estoque");

                    b.HasKey("isn_unidade_medida_estoque");

                    b.ToTable("UnidadeMedidaEstoque");
                });
#pragma warning restore 612, 618
        }
    }
}
